### ISSUE TITLE
Won't install with Mocha 4.X

### ISSUE THREAD

**Issue by JoeTheFkingFrypan** [alaauco/mochawesome-junit-reporter#1]
- [mocha-junit-reporter](https://github.com/michaelleeallen/mocha-junit-reporter) was updated a week ago to add [support of `Mocha 4.X`](https://github.com/michaelleeallen/mocha-junit-reporter/commit/3b5a26c198ead2bcf8d4ad690970772a1fcd2fc6)

Could you bump **mocha-junit-reporter** to `v1.15.0`?

**Comment by JoeTheFkingFrypan** [comment]
Pull request opened related to this issue: https://github.com/alaauco/mochawesome-junit-reporter/pull/2

**Comment by alaauco** [comment]
1.1.0 released
